export type LinkedListLeetcodeQuestion = {
  title: string;
  slug: string;
  leetcodeSlug?: string;
  difficulty: "EASY" | "MEDIUM" | "HARD";
  subtopicId: string;
  affiliatedLessonId: string;
};

export const LINKED_LIST_LEETCODE_QUESTIONS = [
  { title: "Add Two Numbers", slug: "add-two-numbers", difficulty: "MEDIUM", subtopicId: "core-ll-problems", affiliatedLessonId: "linked-list-l05-add-two-numbers" },
  { title: "Add Two Numbers II", slug: "add-two-numbers-ii", difficulty: "MEDIUM", subtopicId: "core-ll-problems", affiliatedLessonId: "linked-list-l05-add-two-numbers" },
  { title: "Add Two Polynomials Represented as Linked Lists", slug: "add-two-polynomials-represented-as-linked-lists", difficulty: "MEDIUM", subtopicId: "core-ll-problems", affiliatedLessonId: "linked-list-l05-add-two-numbers" },
  { title: "All O`one Data Structure", slug: "all-o-one-data-structure", leetcodeSlug: "all-oone-data-structure", difficulty: "HARD", subtopicId: "dll-problems", affiliatedLessonId: "linked-list-l19-pairs-sum-dll" },
  { title: "Convert Binary Number in a Linked List to Integer", slug: "convert-binary-number-in-a-linked-list-to-integer", difficulty: "EASY", subtopicId: "foundations", affiliatedLessonId: "linked-list-l01-introduction" },
  { title: "Convert Binary Search Tree to Sorted Doubly Linked List", slug: "convert-binary-search-tree-to-sorted-doubly-linked-list", difficulty: "MEDIUM", subtopicId: "dll-basics", affiliatedLessonId: "linked-list-l03-doubly-introduction" },
  { title: "Convert Sorted List to Binary Search Tree", slug: "convert-sorted-list-to-binary-search-tree", difficulty: "MEDIUM", subtopicId: "advanced-patterns", affiliatedLessonId: "linked-list-l26-sort-list" },
  { title: "Copy List with Random Pointer", slug: "copy-list-with-random-pointer", difficulty: "MEDIUM", subtopicId: "advanced-patterns", affiliatedLessonId: "linked-list-l27-clone-random" },
  { title: "Delete N Nodes After M Nodes of a Linked List", slug: "delete-n-nodes-after-m-nodes-of-a-linked-list", difficulty: "EASY", subtopicId: "foundations", affiliatedLessonId: "linked-list-l02-deletion-insertion" },
  { title: "Delete Node in a Linked List", slug: "delete-node-in-a-linked-list", difficulty: "MEDIUM", subtopicId: "foundations", affiliatedLessonId: "linked-list-l02-deletion-insertion" },
  { title: "Delete Nodes From Linked List Present in Array", slug: "delete-nodes-from-linked-list-present-in-array", difficulty: "MEDIUM", subtopicId: "foundations", affiliatedLessonId: "linked-list-l02-deletion-insertion" },
  { title: "Delete the Middle Node of a Linked List", slug: "delete-the-middle-node-of-a-linked-list", difficulty: "MEDIUM", subtopicId: "cycle-loop", affiliatedLessonId: "linked-list-l16-delete-middle" },
  { title: "Design a Text Editor", slug: "design-a-text-editor", difficulty: "HARD", subtopicId: "dll-problems", affiliatedLessonId: "linked-list-l19-pairs-sum-dll" },
  { title: "Design Authentication Manager", slug: "design-authentication-manager", difficulty: "MEDIUM", subtopicId: "dll-problems", affiliatedLessonId: "linked-list-l19-pairs-sum-dll" },
  { title: "Design Browser History", slug: "design-browser-history", difficulty: "MEDIUM", subtopicId: "advanced-patterns", affiliatedLessonId: "linked-list-l28-browser-history" },
  { title: "Design Circular Deque", slug: "design-circular-deque", difficulty: "MEDIUM", subtopicId: "cycle-loop", affiliatedLessonId: "linked-list-l14-detect-cycle" },
  { title: "Design Circular Queue", slug: "design-circular-queue", difficulty: "MEDIUM", subtopicId: "cycle-loop", affiliatedLessonId: "linked-list-l14-detect-cycle" },
  { title: "Design Front Middle Back Queue", slug: "design-front-middle-back-queue", difficulty: "MEDIUM", subtopicId: "advanced-patterns", affiliatedLessonId: "linked-list-l28-browser-history" },
  { title: "Design HashMap", slug: "design-hashmap", difficulty: "EASY", subtopicId: "advanced-patterns", affiliatedLessonId: "linked-list-l28-browser-history" },
  { title: "Design HashSet", slug: "design-hashset", difficulty: "EASY", subtopicId: "advanced-patterns", affiliatedLessonId: "linked-list-l28-browser-history" },
  { title: "Design Linked List", slug: "design-linked-list", difficulty: "MEDIUM", subtopicId: "foundations", affiliatedLessonId: "linked-list-l02-deletion-insertion" },
  { title: "Design Most Recently Used Queue", slug: "design-most-recently-used-queue", difficulty: "MEDIUM", subtopicId: "dll-problems", affiliatedLessonId: "linked-list-l19-pairs-sum-dll" },
  { title: "Design Phone Directory", slug: "design-phone-directory", difficulty: "MEDIUM", subtopicId: "advanced-patterns", affiliatedLessonId: "linked-list-l28-browser-history" },
  { title: "Design Skiplist", slug: "design-skiplist", difficulty: "HARD", subtopicId: "advanced-patterns", affiliatedLessonId: "linked-list-l28-browser-history" },
  { title: "Design Twitter", slug: "design-twitter", difficulty: "MEDIUM", subtopicId: "advanced-patterns", affiliatedLessonId: "linked-list-l28-browser-history" },
  { title: "Double a Number Represented as a Linked List", slug: "double-a-number-represented-as-a-linked-list", difficulty: "MEDIUM", subtopicId: "core-ll-problems", affiliatedLessonId: "linked-list-l11-add-one" },
  { title: "Find the Minimum and Maximum Number of Nodes Between Critical Points", slug: "find-the-minimum-and-maximum-number-of-nodes-between-critical-points", difficulty: "MEDIUM", subtopicId: "core-ll-problems", affiliatedLessonId: "linked-list-l13-middle" },
  { title: "Flatten a Multilevel Doubly Linked List", slug: "flatten-a-multilevel-doubly-linked-list", difficulty: "MEDIUM", subtopicId: "advanced-patterns", affiliatedLessonId: "linked-list-l24-flatten" },
  { title: "Flatten Binary Tree to Linked List", slug: "flatten-binary-tree-to-linked-list", difficulty: "MEDIUM", subtopicId: "advanced-patterns", affiliatedLessonId: "linked-list-l24-flatten" },
  { title: "Insert Greatest Common Divisors in Linked List", slug: "insert-greatest-common-divisors-in-linked-list", difficulty: "MEDIUM", subtopicId: "foundations", affiliatedLessonId: "linked-list-l02-deletion-insertion" },
  { title: "Insert into a Sorted Circular Linked List", slug: "insert-into-a-sorted-circular-linked-list", difficulty: "MEDIUM", subtopicId: "cycle-loop", affiliatedLessonId: "linked-list-l14-detect-cycle" },
  { title: "Insertion Sort List", slug: "insertion-sort-list", difficulty: "MEDIUM", subtopicId: "advanced-patterns", affiliatedLessonId: "linked-list-l26-sort-list" },
  { title: "Intersection of Two Linked Lists", slug: "intersection-of-two-linked-lists", difficulty: "EASY", subtopicId: "core-ll-problems", affiliatedLessonId: "linked-list-l12-intersection-y" },
  { title: "LFU Cache", slug: "lfu-cache", difficulty: "HARD", subtopicId: "dll-problems", affiliatedLessonId: "linked-list-l19-pairs-sum-dll" },
  { title: "Linked List Components", slug: "linked-list-components", difficulty: "MEDIUM", subtopicId: "advanced-patterns", affiliatedLessonId: "linked-list-l26-sort-list" },
  { title: "Linked List Cycle", slug: "linked-list-cycle", difficulty: "EASY", subtopicId: "cycle-loop", affiliatedLessonId: "linked-list-l14-detect-cycle" },
  { title: "Linked List Cycle II", slug: "linked-list-cycle-ii", difficulty: "MEDIUM", subtopicId: "cycle-loop", affiliatedLessonId: "linked-list-l17-cycle-start" },
  { title: "Linked List in Binary Tree", slug: "linked-list-in-binary-tree", difficulty: "MEDIUM", subtopicId: "foundations", affiliatedLessonId: "linked-list-l01-introduction" },
  { title: "Linked List Random Node", slug: "linked-list-random-node", difficulty: "MEDIUM", subtopicId: "core-ll-problems", affiliatedLessonId: "linked-list-l13-middle" },
  { title: "LRU Cache", slug: "lru-cache", difficulty: "MEDIUM", subtopicId: "dll-problems", affiliatedLessonId: "linked-list-l19-pairs-sum-dll" },
  { title: "Max Stack", slug: "max-stack", difficulty: "HARD", subtopicId: "dll-problems", affiliatedLessonId: "linked-list-l19-pairs-sum-dll" },
  { title: "Maximum Twin Sum of a Linked List", slug: "maximum-twin-sum-of-a-linked-list", difficulty: "MEDIUM", subtopicId: "core-ll-problems", affiliatedLessonId: "linked-list-l10-palindrome" },
  { title: "Merge In Between Linked Lists", slug: "merge-in-between-linked-lists", difficulty: "MEDIUM", subtopicId: "advanced-patterns", affiliatedLessonId: "linked-list-l23-merge-two-sorted" },
  { title: "Merge k Sorted Lists", slug: "merge-k-sorted-lists", difficulty: "HARD", subtopicId: "advanced-patterns", affiliatedLessonId: "linked-list-l25-merge-k-sorted" },
  { title: "Merge Nodes in Between Zeros", slug: "merge-nodes-in-between-zeros", difficulty: "MEDIUM", subtopicId: "advanced-patterns", affiliatedLessonId: "linked-list-l23-merge-two-sorted" },
  { title: "Merge Two Sorted Lists", slug: "merge-two-sorted-lists", difficulty: "EASY", subtopicId: "advanced-patterns", affiliatedLessonId: "linked-list-l23-merge-two-sorted" },
  { title: "Middle of the Linked List", slug: "middle-of-the-linked-list", difficulty: "EASY", subtopicId: "core-ll-problems", affiliatedLessonId: "linked-list-l13-middle" },
  { title: "Minimum Pair Removal to Sort Array I", slug: "minimum-pair-removal-to-sort-array-i", difficulty: "EASY", subtopicId: "dll-problems", affiliatedLessonId: "linked-list-l19-pairs-sum-dll" },
  { title: "Next Greater Node In Linked List", slug: "next-greater-node-in-linked-list", difficulty: "MEDIUM", subtopicId: "core-ll-problems", affiliatedLessonId: "linked-list-l09-reverse-linked-list" },
  { title: "Odd Even Linked List", slug: "odd-even-linked-list", difficulty: "MEDIUM", subtopicId: "core-ll-problems", affiliatedLessonId: "linked-list-l06-odd-even" },
  { title: "Palindrome Linked List", slug: "palindrome-linked-list", difficulty: "EASY", subtopicId: "core-ll-problems", affiliatedLessonId: "linked-list-l10-palindrome" },
  { title: "Partition List", slug: "partition-list", difficulty: "MEDIUM", subtopicId: "advanced-patterns", affiliatedLessonId: "linked-list-l26-sort-list" },
  { title: "Plus One Linked List", slug: "plus-one-linked-list", difficulty: "MEDIUM", subtopicId: "core-ll-problems", affiliatedLessonId: "linked-list-l11-add-one" },
  { title: "Populating Next Right Pointers in Each Node", slug: "populating-next-right-pointers-in-each-node", difficulty: "MEDIUM", subtopicId: "core-ll-problems", affiliatedLessonId: "linked-list-l09-reverse-linked-list" },
  { title: "Populating Next Right Pointers in Each Node II", slug: "populating-next-right-pointers-in-each-node-ii", difficulty: "MEDIUM", subtopicId: "core-ll-problems", affiliatedLessonId: "linked-list-l09-reverse-linked-list" },
  { title: "Remove Duplicates From an Unsorted Linked List", slug: "remove-duplicates-from-an-unsorted-linked-list", difficulty: "MEDIUM", subtopicId: "advanced-patterns", affiliatedLessonId: "linked-list-l26-sort-list" },
  { title: "Remove Duplicates from Sorted List", slug: "remove-duplicates-from-sorted-list", difficulty: "EASY", subtopicId: "dll-problems", affiliatedLessonId: "linked-list-l20-remove-duplicates-dll" },
  { title: "Remove Duplicates from Sorted List II", slug: "remove-duplicates-from-sorted-list-ii", difficulty: "MEDIUM", subtopicId: "advanced-patterns", affiliatedLessonId: "linked-list-l26-sort-list" },
  { title: "Remove Linked List Elements", slug: "remove-linked-list-elements", difficulty: "EASY", subtopicId: "foundations", affiliatedLessonId: "linked-list-l02-deletion-insertion" },
  { title: "Remove Nodes From Linked List", slug: "remove-nodes-from-linked-list", difficulty: "MEDIUM", subtopicId: "foundations", affiliatedLessonId: "linked-list-l02-deletion-insertion" },
  { title: "Remove Nth Node From End of List", slug: "remove-nth-node-from-end-of-list", difficulty: "MEDIUM", subtopicId: "core-ll-problems", affiliatedLessonId: "linked-list-l08-remove-nth-from-end" },
  { title: "Remove Zero Sum Consecutive Nodes from Linked List", slug: "remove-zero-sum-consecutive-nodes-from-linked-list", difficulty: "MEDIUM", subtopicId: "foundations", affiliatedLessonId: "linked-list-l02-deletion-insertion" },
  { title: "Reorder List", slug: "reorder-list", difficulty: "MEDIUM", subtopicId: "advanced-patterns", affiliatedLessonId: "linked-list-l26-sort-list" },
  { title: "Reverse Linked List", slug: "reverse-linked-list", difficulty: "EASY", subtopicId: "core-ll-problems", affiliatedLessonId: "linked-list-l09-reverse-linked-list" },
  { title: "Reverse Linked List II", slug: "reverse-linked-list-ii", difficulty: "MEDIUM", subtopicId: "advanced-patterns", affiliatedLessonId: "linked-list-l21-reverse-k-group" },
  { title: "Reverse Nodes in Even Length Groups", slug: "reverse-nodes-in-even-length-groups", difficulty: "MEDIUM", subtopicId: "advanced-patterns", affiliatedLessonId: "linked-list-l21-reverse-k-group" },
  { title: "Reverse Nodes in k-Group", slug: "reverse-nodes-in-k-group", difficulty: "HARD", subtopicId: "advanced-patterns", affiliatedLessonId: "linked-list-l21-reverse-k-group" },
  { title: "Rotate List", slug: "rotate-list", difficulty: "MEDIUM", subtopicId: "advanced-patterns", affiliatedLessonId: "linked-list-l22-rotate" },
  { title: "Sort List", slug: "sort-list", difficulty: "MEDIUM", subtopicId: "advanced-patterns", affiliatedLessonId: "linked-list-l26-sort-list" },
  { title: "Spiral Matrix IV", slug: "spiral-matrix-iv", difficulty: "MEDIUM", subtopicId: "advanced-patterns", affiliatedLessonId: "linked-list-l26-sort-list" },
  { title: "Split Linked List in Parts", slug: "split-linked-list-in-parts", difficulty: "MEDIUM", subtopicId: "advanced-patterns", affiliatedLessonId: "linked-list-l21-reverse-k-group" },
  { title: "Steps to Make Array Non-decreasing", slug: "steps-to-make-array-non-decreasing", difficulty: "MEDIUM", subtopicId: "advanced-patterns", affiliatedLessonId: "linked-list-l26-sort-list" },
  { title: "Swap Nodes in Pairs", slug: "swap-nodes-in-pairs", difficulty: "MEDIUM", subtopicId: "advanced-patterns", affiliatedLessonId: "linked-list-l21-reverse-k-group" },
  { title: "Swapping Nodes in a Linked List", slug: "swapping-nodes-in-a-linked-list", difficulty: "MEDIUM", subtopicId: "core-ll-problems", affiliatedLessonId: "linked-list-l08-remove-nth-from-end" },
] as const satisfies readonly LinkedListLeetcodeQuestion[];
